#include "log_create.h"
#include <stdio.h>
#include <stdlib.h>

/*
 *
 *
 *
 * Author: Logan Thompson
 * Date: 03/29/2019
 *
 *
 * ToDo:
 */

/*
 * Function: readUserLogEntry
 * Input:string
 * Output: MovieLog pointer
 *
 * Returns pointer to a MovieLog object created using the string passed to it
 *
 * ToDo:
 */
MovieLog * readUserLogEntry(char *line)
{
	char *title = strtok(line,"\t");
	char *genres = strtok(NULL,"\t");
	char *runtime = strtok(NULL,"\t");
	char *releaseYear = strtok(NULL,"\t");
	char *dvd = strtok(NULL,"\t");
	char *bluray = strtok(NULL,"\t");
	char *digital = strtok(NULL,"\t");
	char *date = strtok(NULL,"\t");



	MovieLog *ret = newMovieLogFile(title, atoi(releaseYear), atoi(runtime), genres, atoi(dvd), atoi(bluray), atoi(digital), date);
	return ret;
}

/*
 * Function: importLogFile
 * Input: string file name
 * Output: tree pointer
 *
 * returns a pointer to a tree generated by reading in the file name passed to it
 *
 * ToDo:
 */
tree * importLogFile(char *fname)
{
	FILE *fp;
	char buf[460];
	tree *ret = newTree(begLogMatch, printMovieLog, logTitleLessThan, logTitleGreaterThan, printMovieLogScreen);

	fp = fopen(fname,"r");

	while(fgets(buf,460,fp) != NULL)
	{
		if(!(strcmp(buf,"\n") == 0))
		{
			MovieLog *entry = readUserLogEntry(buf);
			insert(ret,newNode(entry));
		}
	}

	fclose(fp);
	return ret;
}

/*
 * Function: exportLogFile
 * Input: tree, file name
 * Output:None
 *
 * Prints tree contents in order to file name specified
 *
 * ToDo:
 */
void exportLogFile(tree *Tree, char *fname)
{
	FILE *fp;

	fp = fopen(fname,"w");

	inOrder(Tree,fp);

	fclose(fp);
}

int ifExists(const char *fName)
{
	FILE *fp;

	if((fp = fopen(fName,"r")))
	{
		fclose(fp);
		return 1;
	}
	return 0;
}
